users:
  - default
  - name: vmadmin
    sudo:  ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdX3VCEGewx0NqhAbG0tR/WX0NdsjIld3lmeP0O805gEoJ3tdLaxowkyn9/W1/B7eHDFKFggbdB7tymaahKcnB8HXFJZDS0LRC6x44tGfkne0NNlRLTK8oZnZuEcT/BnZh6sysm/grznWYe35EdDkEbYnngYBf2ouRBw0ZLxRHa1LyLYa/UkiKXC9oc1sYJkxa31UQ+19mBYofB68TYNjimaBFyehbogHUpdJD1UNtAadNVbpbaxnuW1hzuLz4/CZ3CmUK1rokBx/z3g2C+44E8fT4n1o6v9Df9IfLFc3oPEppVtrPF8Zn2LTM4ggL7IBiHojZD9wAkXMl1B7ZSbI9mvdcQJ9x6jm99m0Q43xNquhfp4p1noeAnCVzMXiRzWIqiqBMar6S62acBsHw9pYSUD/UemwJdT/Sf/uxGg6R/v/ZB6ZU83fjn6W0rRurLZ/rYbLz+NisVJArx22mGD16YmZLsvY7h0OCWjYL2NDSuGlRa/NMtHz0dRDqqeBN14E= vmadmin