users:
  - default
  - name: vmadmin
    sudo:  ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDVIaKUgd+fk56kc0ZesCHj7Te4qRuWu1XIeeNxGzfY9ch0I/tUB3Fy+6FUyFgZs4bQRm05g4Ju6lFjSMcQ5oOTMrL9/MAYBMjDz4EArWtJOWtXbXo8SQ4SMYcZa81SyVLp11EOPd7x/GkGrbgfevE2qNBZ7opAO7WtZEm7uw43pCxQe39vy6UGYNgD5py2h7fayNecAU9HDpEgeLcsJ91+TPg02A599zFPJNWyhUWUxLKdhH6pa+LNDX0JH1//oWrUM09Z4keTgsI6/Nj9mX4vKJ/AIPE3B7tTb6DeA66UFCuFZuXIG4BgeLtfP90EqY3Q2MUlwb4YustodYLnRznRPRxBQEAz0YYAXMULR7383OXh89aXnULYvLB2I+5DHiLsUwOx48HQHSRaFLgP61c/3P1nAYKrpH3ObhmykCYF/3SUlL52JBj/1+79RrmyRQzuXV84nPp/oFYqNwhzbEWYnDFgXSHK1+ZoxpABewVctHYMoCztXgkauhN9HMUgZkE= vmadmin