users:
  - default
  - name: vmadmin
    sudo:  ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCq4O7NfR4CgNBTSY5bThcGTzfUl8FKi1qOUa7eYBcxmLkRAfLNxyVUIYDk2iXUUwQs0TqwhYqzakss0WKkhq+4PXFrN51SaLYec+X6h6TdIuUi1TSTUT5u4iuQeqNYHdLeal/BZS9fRtLJYAE3Cq65qcd46AOnlX8pB6b8RF4QRsJn+Vt9qn+TmXm57TSwCwLPP42DlJwUWx6ct92wshWE+byBW7x7xXofS4eLkISr5cF911b0JcZkl3mgugJx6R+VFBW8RjJPgpUAGI8ianEfH0zihZYAYn2smei2gilAFRJ+yKAdheh4J0QEnNgdQOglf+8xx+f5XsBM4/Z93ZbnHBwySSS5I4U2blvKbBWLRLTcrTQuiMOeBy48qr/Of7fAAy8EHpVw1Pet8OMTdFgCWGi/Fotz/RPFzgxJjx1lG5R5svProXrbIPaCnFN4nRp8gbvB9wGUFhI6qWLtERBSLpOyyI5RCL4LHDpnMUGlIbAtpeW+ydq+PNhGJgdNpA0= vmadmin