users:
  - default
  - name: vmadmin
    sudo:  ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDYCDPbTS4HmRLT6xpJaGEMy6lRVxVvLZejxQghYulDmXtxg4AanSs8bHxrUREtkIJ7Z+2MOabmoeZl/2EEUD9YuWz65XzW6jqBaJTuwReyGgx/wGtiOkh5woRUaGUzPci4OqH23yJ2FCFZ0y9+scZN9CKhduQ5jUIkzv4mA6ELtLml/5CVAXIWZQM7YvfLnLL/hh8RHvZkyp2v8TSZRQLBRlf1edssIitzF9IkoBx9pBEiauflRsdd0wVJM/47AJBwDCIyKXtnxQL0GuTJkJ+s1v9jvWVwL4kio0AZbQnXilxd6iJ16hnWGh/m/R2QvNjFbI3Jdlb/dCgjNn0+eWpypbx2bm/JtpEA6d83t2T1nU8+djmAbkwAVtoqpxPRuZH9U5FYhQFm194gTwX6beYCb+f69lmsyVsn++2+ZJ9J0dDTUYZRVU5ZLrm5Tar+/48qGc5d8K2cg0HKD1o+XtNKyP/MIOTxTYJk4FPZIp1GjF/XxaO+HUSxLmFBgeriexE= vmadmin