users:
  - default
  - name: vmadmin
    sudo:  ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCv2sWZPiQyTG+Ja9j+cPFUCcKnNWrsdhLzlHZq3wGMkVBRYR9snte9pRlA8AWN3ttasD2pVR9Bfo5I5JY5MpPrwXwMMr6cuxMOgN9GjwfAXhAhPZphb/l7lwXNwwnIPA8reRupQx3Vk7uopZOtSACdkvy5ADYa52WhNPfvGp0z3PsJ6qr4QkZAEk/ZyHlQt+DgcHfMivPAeQKxo0PjxFPfX4xumM15qSs4rNjHv8Fw433WXpm+1DwrDj2jooLJPh+YsEEZ7KtR4QboysgG4fDyirutrEDm+VV3kWqH4PUCYioY3oZNiBEvmSN9z0Y6LTY845ynYF3ZjTBQM65hi2mCHToqAsTcDpJf0KEc7mRIXx70foLyvMSIdhLO8Et+jVm8t1m/vmPBjvyneSEEhO4bGSUDSfK5t+GJZbdi6HDfQIRp1OJl6qtTHvv6EyAAjrFhUTGK42FpWVDMQ/LmJd2RcieODXMdGjj+6GQxFCJgTsjUMFDadQGjl72je7dkmsU= vmadmin