---
- name: Create Multipass VMs for a IP3 cluster
  hosts: localhost

  tasks:
  - name: Read IP3 cluster node VM configuration from file
    include_vars:
      file: ip3-nodes.yml
      name: ip3nodes
  - name: Create keypair and cloud-init
    include_tasks: create-keys-and-cloudinit.yml
  - name: Create the IP3 cluster VMs
    include_tasks: delete-and-create-new-vm-tasks.yml
    vars:
      vmname: "{{ item.key }}"
      vmcreationparams: "{{ item.value }}"
    loop: "{{ ip3nodes | dict2items }}"