---
- name: Create Multipass VMs for a IP3 cluster
  hosts: all
  vars:
    mydir: "/home/vmadmin/yolo/"

  tasks:
  - name: Read IP3 cluster node VM configuration from file
    include_vars:
      file: ip3-nodes.yml
      name: ip3nodes
  - name: Create keypair and cloud-init
    include_tasks: create-keys-and-cloudinit.yml
  - name: Create the IP3 cluster VMs
    include_tasks: delete-and-create-new-vm-tasks.yml
    vars:
      vmname: "{{ item.key }}"
      vmcreationparams: "{{ item.value }}"
    loop: "{{ ip3nodes | dict2items }}"
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: "/home/vmadmin/yolo/"
      state: directory
      mode: '0755'  
  